### PR TITLE
Code Mirror Integration

### PR DESCRIPTION
**Pull request by 55sketch**
Added Syntax highlighting through CodeMirror

### CODE REVIEW

**Comment by spite** [comment]
This is super nice! I was thinking on adding a toggle in case people don't want to wait the extra 100ms to load CM, but this seems to be fast, really fast.

One minor issue i've see testing: long content seems to break the layout:

screen shot 2016-02-24 at 23 31 48

May be you can take a look at that? Excellent work all the same :D

**Comment by 55sketch** [comment]
Ah cool - I hadn't checked that. Should be as simple as matching the CSS rules from the textarea on the CodeMirror element. I'll take a look and create a new PR.

**Comment by 55sketch** [comment]
Done - think that should work

**Comment by spite** [comment]
Perfect! It's pushed to the Chrome Store, v0.5
https://chrome.google.com/webstore/detail/sketchtab/ioonoapnncbgnhjfjipkfbkpkogmknlm
Thanks so much!

**Pull request merged**
